[package]
name = "ads1110-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-time = "0.2.0"
embedded-hal-async = "1.0.0-rc.2"
